import json
import uuid
from pathlib import Path
from typing import Union, List
from datetime import datetime
import pandas as pd


REQUIRED_COLUMNS = [
    "timestamp",
    "machine_id",
    "machine_type",
    "status",
    "cycle_time",
    "produced_units",
    "defective_units",
    "energy_kw",
    "temperature_c",
    "vibration_mm_s"
]


# =========================
# LOAD BRONZE (RAW INGEST)
# =========================
def load_bronze(path: Union[Path, str]) -> pd.DataFrame:
    """
    Loads Raw jsonb generated by data_simulator.
    It accepts Array JSON or JSON lines.
    """

    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    # Detects if is JSON line
    with open(path, "r", encoding="utf-8") as f:
        first_char = f.read(1)

    if first_char == "[":
        # Traditional JSON
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        df = pd.DataFrame(data)
    else:
        # JSON Lines
        df = pd.read_json(path, lines=True)

    # Schema Validation
    missing = set(REQUIRED_COLUMNS) - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in bronze layer: {missing}")

    # Basic Conversions
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

    numeric_cols = [
        "cycle_time",
        "produced_units",
        "defective_units",
        "energy_kw",
        "temperature_c",
        "vibration_mm_s"
    ]

    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # =========================
    # INGESTION METADATA
    # =========================
    df["ingestion_timestamp"] = datetime.utcnow()
    df["batch_id"] = str(uuid.uuid4())

    return df


# =========================
# SAVE BRONZE (APPEND ONLY)
# =========================
def save_bronze(
    df: pd.DataFrame,
    output_root: Union[Path, str] = "data_lake/bronze/telemetry_events"
):
    """
    Salva dados na bronze de forma particionada por data.
    Nunca sobrescreve.
    """

    output_root = Path(output_root)

    df["year"] = df["timestamp"].dt.year
    df["month"] = df["timestamp"].dt.month
    df["day"] = df["timestamp"].dt.day

    for (year, month, day), group in df.groupby(["year", "month", "day"]):
        partition_path = (
            output_root /
            f"year={year}" /
            f"month={month:02d}" /
            f"day={day:02d}"
        )

        partition_path.mkdir(parents=True, exist_ok=True)

        file_name = f"batch_{group['batch_id'].iloc[0]}.parquet"

        group.drop(columns=["year", "month", "day"]).to_parquet(
            partition_path / file_name,
            index=False
        )